# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("accessibility.typeaheadfind.flashBar", 0);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1457825287);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1457825407);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1457904242);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1457827184);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1457900521);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 1);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.panel.shown", true);
user_pref("browser.migration.version", 22);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.introShown", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20141113113219");
user_pref("browser.slowStartup.averageTime", 7102);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20141113113219");
user_pref("browser.startup.homepage_override.mstone", "33.1");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":3}");
user_pref("browser.uitour.whitelist.add.260", "");
user_pref("browser.uitour.whitelist.add.340", "");
user_pref("datareporting.healthreport.lastDataSubmissionRequestedTime", "1457827864148");
user_pref("datareporting.healthreport.lastDataSubmissionSuccessfulTime", "1457827865268");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1457914265268");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAccepted", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1457827126687");
user_pref("datareporting.policy.dataSubmissionPolicyResponseTime", "1457827830084");
user_pref("datareporting.policy.dataSubmissionPolicyResponseType", "accepted-info-bar-dismissed");
user_pref("datareporting.policy.firstRunTime", "1457480858059");
user_pref("datareporting.sessions.current.activeTicks", 4);
user_pref("datareporting.sessions.current.firstPaint", 6712);
user_pref("datareporting.sessions.current.main", 1322);
user_pref("datareporting.sessions.current.sessionRestored", 8792);
user_pref("datareporting.sessions.current.startTime", "1457907370459");
user_pref("datareporting.sessions.current.totalTime", 36);
user_pref("datareporting.sessions.currentIndex", 15);
user_pref("datareporting.sessions.previous.10", "{\"s\":1457835767816,\"a\":1,\"t\":19,\"c\":false,\"m\":973,\"fp\":5101,\"sr\":7964}");
user_pref("datareporting.sessions.previous.11", "{\"s\":1457850169268,\"a\":4,\"t\":29,\"c\":false,\"m\":683,\"fp\":1784,\"sr\":2580}");
user_pref("datareporting.sessions.previous.12", "{\"s\":1457854246745,\"a\":41,\"t\":970,\"c\":true,\"m\":135,\"fp\":1208,\"sr\":1743}");
user_pref("datareporting.sessions.previous.13", "{\"s\":1457900394171,\"a\":248,\"t\":4947,\"c\":true,\"m\":1593,\"fp\":10856,\"sr\":13361}");
user_pref("datareporting.sessions.previous.14", "{\"s\":1457905553275,\"a\":11,\"t\":88,\"c\":true,\"m\":226,\"fp\":2913,\"sr\":4501}");
user_pref("datareporting.sessions.previous.7", "{\"s\":1457827063943,\"a\":132,\"t\":4239,\"c\":true,\"m\":82,\"fp\":873,\"sr\":1274}");
user_pref("datareporting.sessions.previous.8", "{\"s\":1457831566329,\"a\":2,\"t\":7,\"c\":true,\"m\":185,\"fp\":1074,\"sr\":1785}");
user_pref("datareporting.sessions.previous.9", "{\"s\":1457831681924,\"a\":0,\"t\":6,\"c\":false,\"m\":418,\"fp\":1864,\"sr\":2339}");
user_pref("datareporting.sessions.prunedIndex", 6);
user_pref("dom.mozApps.used", true);
user_pref("extensions.blocklist.pingCountTotal", 3);
user_pref("extensions.blocklist.pingCountVersion", 3);
user_pref("extensions.bootstrappedAddons", "{\"langpack-es-ES@firefox.mozilla.org\":{\"version\":\"33.1\",\"type\":\"locale\",\"descriptor\":\"/home/junkcarlos/.mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/langpack-es-ES@firefox.mozilla.org.xpi\"}}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:33.1");
user_pref("extensions.getAddons.cache.lastUpdate", 1457825293);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib64/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1417639513000,\"rdfTime\":1415879628000}}},{\"name\":\"app-system-user\",\"addons\":{\"langpack-es-ES@firefox.mozilla.org\":{\"descriptor\":\"/home/junkcarlos/.mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/langpack-es-ES@firefox.mozilla.org.xpi\",\"mtime\":1415879864000}}}]");
user_pref("extensions.lastAppVersion", "33.1");
user_pref("extensions.lastPlatformVersion", "33.1");
user_pref("extensions.pendingOperations", false);
user_pref("gecko.buildID", "20141113113219");
user_pref("gecko.mstone", "33.1");
user_pref("idle.lastDailyNotification", 1457825184);
user_pref("media.gmp-gmpopenh264.lastUpdate", 1457481236);
user_pref("media.gmp-gmpopenh264.version", "1.1");
user_pref("media.gmp-manager.lastCheck", 1457824989);
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1457827864);
user_pref("places.history.expiration.transient_current_max_pages", 52471);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1457649144);
user_pref("toolkit.startup.last_success", 1457907371);
user_pref("toolkit.telemetry.previousBuildID", "20141113113219");
